config/routes.rb
Rails.application.routes.draw do
   resources :groceries
   resources :categories do
    resources :groceries, only: [:index]
   end
    # root 'welcome#index'
   root :to => "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
 validates :name, presence: true
  has_many :category_groceries
  has_many :groceries, through: :category_groceries
end

app/models/category_grocery.rb
class CategoryGrocery < ActiveRecord::Base
  belongs_to :category
  belongs_to :grocery
end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
  validates :name, presence: true
  has_many :category_groceries
  has_many :categories, through: :category_groceries
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  scope :by_name, ->{ order('name desc') }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  add_crumb "Home", '/'
  protect_from_forgery with: :exception

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category=Category.new()
    add_crumb "Add new category", 'new_category'
  end

  def create
    @category =Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def index
    @categories = Category.all
  end

  def edit
    @category= Category.find(params[ :id])
    add_crumb "Edit Category",'edit_category'
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:category] = "Post successfully updated."
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category= Category.find(params[ :id])
    @category.destroy
    redirect_to categories_path, notice: "Post successfully deleted."
  end
  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController

  def new
    @grocery= Grocery.new()
    @category = Category.new()
     add_crumb "Add new grocery list", 'new_grocery'
  end

  def create
    # debugger
    @grocery =Grocery.new(grocery_params)
    if @grocery.save
      redirect_to groceries_path
    else
      render 'new'
    end
  end

  def show
    @grocery= Grocery.find(params[ :id])
  end

  def index
    @category_filter = params[:category_id]
    @groceries = if @category_filter
      add_crumb "grocery list", 'grocery'
      @category = Category.find(@category_filter)
      @category.groceries.by_name
    else
      add_crumb "grocery lists", 'groceries'
      Grocery.by_name
    end
  end

  def edit
    add_crumb "Edit grocery list", 'edit_grocery'
    @grocery= Grocery.find(params[ :id])

  end

  def update
    # debugger
    @grocery = Grocery.find(params[:id])
    if @grocery.update(grocery_params)
      if request.xhr?
        render nothing: true
      else
        redirect_to :action => 'index'
      end
    else
      request.xhr? ? render(nothing: true, status: :unprocessable_entity) : render('edit')
    end
  end

  def destroy
    @grocery= Grocery.find(params[ :id])
    @grocery.destroy

    redirect_to groceries_path
  end

  private
  def grocery_params
    params.require(:grocery).permit(:name, :number, :category, :explanation, :bought, :photo , category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon_link icon, name, url, link_options = {}
    link_options[:class] ||= ''
    link_options[:class] = link_options[:class] + ' btn btn-link'

    link_to url, link_options do
      content_tag(:span, '', class: "glyphicon glyphicon-#{icon}") + name
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/views/categories/_category.html.erb
<tr>
  <td> <%= category.name %> </td>
  <td>
    <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-link btn-xs', 'aria-hidden' => 'true' %>
    <%= link_to 'Destroy' ,  category_path(category), method: :delete, data: { confirm: 'Are u sure?'},  class: 'glyphicon glyphicon-trash'%>
    <%= link_to 'Groceries' ,  category_groceries_path(category),  class: 'glyphicon glyphicon-list'%>

  </td>
</tr>

app/views/categories/_errorValidation.html.erb
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited
      this category from being saved:</h2>
    <% end %>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    </ul>
  </div>
<% end %>

app/views/categories/_error_validation.html.erb
<div id="error_explanation">
  <% if @category.errors.any? %>
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited
      this category from being saved:
    </h2>
  <% end %>
  <% @category.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</div>

app/views/categories/_form.html.erb
<form class: "form-inline" role: "form">
  <%= render_crumbs %>
  <div class="form-group">
    <%= f.label :"Category name" %><br>
    <%= f.text_field :name %>
    <%= f.submit class: 'btn btn-default btn-xs'%><br>
    <%= link_to "Back", categories_path, class: 'btn btn-link btn-xs', class: 'glyphicon glyphicon-arrow-left aria-hidden="true"' %>
    <%= link_to "Home", categories_path, class: 'btn btn-link btn-xs', class: 'glyphicon glyphicon-home aria-hid' %>
  </div>
</form>

app/views/categories/edit.html.erb
<%= form_for :category, url: category_path(@category), method: :patch do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/categories/index.html.erb
<h2>Categories list</h2>
<table class="table table-hover table-striped">
  <thead>
    <h4> category name </h4>
  </thead>
  <tbody>
    <tr> <%= render partial: 'category', collection: @categories %></tr>
  </tbody>
</table>
<%= link_to 'NewCategory', new_category_path, class: 'btn btn-link btn-xs', class: 'glyphicon glyphicon-plus aria-hidden="true"' %>
<%= link_to 'groceries_list', groceries_path, class: 'btn btn-link btn-xs', class: 'glyphicon glyphicon-tasks' %>


 <% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

app/views/categories/new.html.erb
<%= form_for :category, url: categories_path  do |f| %>
  <%= render partial: 'error_validation'%>
  <%= render partial: 'form', locals: {f: f} %>
<% end%>

app/views/groceries/_form.html.erb
<form>
   <%= render_crumbs %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :explanation %><br>
    <%= f.text_area :explanation %>
  </p>
  <p>
    <%= f.label :bought %><br>
    <%= f.check_box :bought, {}, "true", "false"%>
  </p>
  <p>
    <% Category.all.each do |category| %>
      <%= check_box_tag "grocery[category_ids][]", category.id, @grocery.category_ids.include?(category.id) %>
      <%= category.name%>
    <% end %>
  </p>



  <span class="btn btn-default fileinput-button">
    <%= f.file_field :photo %>
  </span>

  <%= f.submit class: 'btn btn-default btn-xs'%><br>
  <%= link_to "Back", groceries_path, class: 'btn btn-link btn-xs', class: 'glyphicon glyphicon-arrow-left aria-hidden="true"' %>
  <%= link_to "Home", categories_path, class: 'btn btn-link btn-xs', class: 'glyphicon glyphicon-home aria-hidden="true"' %>

</form>

app/views/groceries/_grocery.html.erb
<tr>
  <% unless @category_filter %>
    <td><%= grocery.categories.map {|c| c.name}.join(', ') %></td>
  <% end %>
  <td> <%= grocery.name %></td>
  <td><%= grocery.number %></td>
  <td><%= grocery.explanation %></td>
  <td><%= grocery.bought ? 'yes' : 'no' %></td>
  <td>
    <%= form_for grocery, url: grocery_path(grocery), method: :patch  do |f| %>
      <%= f.check_box :bought,{ class: 'bought_check' }, "true", "false"%>
       <%= f.submit class: 'btn btn-default btn-xs'%><br>
    <% end %>
  </td>
  <td>
    <% if grocery.photo_file_name.present? %>
      <%= image_tag grocery.photo.url(:thumb) %>
    <% end %>
  </td>

  <td> <%= icon_link 'pencil', 'Edit', edit_grocery_path(grocery) %></td>
  <td> <%= icon_link 'trash', 'Destroy', grocery_path(grocery), method: :delete, data: { confirm: 'Are u sure'} %></td>

</tr>

app/views/groceries/edit.html.erb
<h1>Editing grocery</h1>

<%= form_for :grocery, url: grocery_path(@grocery), method: :patch do |f| %>
  <% if @grocery.errors.any? %>
    <div id="error_explanation">
      <h2> <%= pluralize(@grocery.errors.count, "error") %> prohibited
        this grocery from being saved:</h2>
      <% end %>
      <ul>
        <% @grocery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      </ul>
    </div>
  <% end %>

  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/groceries/index.html.erb
 <%= render_crumbs %>
<h1>Grocery List</h1>
<table class="table table-hover table-striped">
  <tr>
   <% unless @category_filter %>
    <th> Category </th>
   <% end %>
   <th> Name</th>
   <th> Number</th>
   <th> Explanation</th>
   <th> Bought</th>
   <th> Photo</th>
   <th> </th>
   <th> </th>

  <%= render partial: 'grocery', collection: @groceries %>
  </table>
  <%= icon_link 'plus', 'New grocery list', new_grocery_path %>
  <%= icon_link 'list', 'Category list', categories_path %>

 <% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= icon_link 'home', 'Home', categories_path %>

app/views/groceries/new.html.erb
<%= form_for :grocery, url: groceries_path  do |f| %>
  <% if @grocery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grocery.errors.count, "error") %> prohibited
        this grocery from being saved:</h2>
      <% end %>
      <ul>
        <% @grocery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      </ul>
    </div>
  <% end %>
  <%= render partial: 'form', locals: {f: f} %>

<% end %>

app/views/groceries/show.html.erb
<%= link_to 'Groceries overview', groceries_path %>
<table class="table table-striped table-bordered table-condensed">
  <tr>
   <th> Category  .</th>
   <th> Name  .</th>
   <th> Number  .</th>
   <th> Explanation  .</th>
   <th> Bought  .</th>
  </tr>
  <tr>
    <td>
      <ul>
        <% @grocery.categories.each do |category| %>
          <li><%= category.name %></li>
        <% end %>
      </ul>
    </td>
    <td> <%= @grocery.name %></td>
    <td><%= @grocery.number %></td>
    <td><%= @grocery.explanation %></td>
    <td><%= @grocery.bought %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GroceryList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div id="main-container" class="container-fluid">
      <div class="navbar-header pade-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
          <i class="fa fa-bar"></i>
        </button>
      </div>
      <div class="row">
          <div class=" col-md-3"></div>
          <div class="col-xs-12 col-sm-12 col-md-6">


            <%= yield %>

          </div>
          <div class="col-md-3"></div>
      </div>
    </div>

</body>
</html>